---

- name: 'Debian: Install APT dependencies'
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https

- name: 'Debian: Add influxdata GPG key'
  apt_key:
    url: "{{ influxdata__gpg_url }}"

- name: 'Debian: Add influxdata APT repository'
  apt_repository:
    repo: "{{ influxdata__apt_repo }}"
    state: present
    update_cache: yes
